### ISSUE TITLE
Should WebRx incorporate some default filters?

### ISSUE THREAD

**Issue by oliverw** [WebRxJS/WebRx#1]
Should WebRx incorporate some default filters? Good candidates would be ports of Angular's [currency, number an date filters](https://github.com/angular/angular.js/blob/master/src/ng/filter/filters.js).

**Comment by PhiLhoSoft** [comment]
Personally, I dislike the term 'filter', as I find it a bit misleading. The first time I found it in AngularJS, I expected to get less data on output than on input...
I would prefer the term 'formatter' or similar.
Unless I miss some use cases of these filters.

**Comment by oliverw** [comment]
You got a point Phillipe. On the other hand one could argue that the term sounds familiar to people coming from an Angular background.
