### ISSUE TITLE
no invokeCommand function

### ISSUE THREAD

**Issue by patsissons** [WebRxJS/WebRx#11]
I wrote a (hopefully stable) `Rx.Observable<T>.invokeCommand(wx.ICommand<TResult>)` function tonight because I needed that behaviour. I modeled the function off of [ReactiveUI's function](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ReactiveCommand.cs#L511) by the same name. This function allows you to build a stream and dump the results directly into an existing command (very handy for doing view to viewmodel communication).

here is the code I am using, it is working so far for me and should be easy to integrate into your code base.

```ts
/// <reference path="../typings/webrx/web.rx.d.ts" />

'use strict';

declare module Rx {
  export interface Observable<T> extends IObservable<T> {
    invokeCommand(command: wx.ICommand<any>): Rx.IDisposable;
  }
}

function invokeCommand<T, TResult>(command: wx.ICommand<TResult>) {
  // prime the command's canExecute (otherwise it will always return false when called in the observable stream)
  // this may be a scheduling problem? hard to tell.
  command.canExecute(null);
  return (this as Rx.Observable<T>)
    // debounce typings want the (incorrectly named) durationSelector to return a number here
    // either fix the typing file or do a .select(_ => 0) after the where to fix this
    .debounce(x => command.canExecuteObservable.startWith(command.canExecute(x)).where(b => b))
    .select(x => command.executeAsync(x).catch(Rx.Observable.empty<TResult>()))
    .switch()
    .subscribe();
}

(<any>Rx.Observable).prototype.invokeCommand = invokeCommand;
```

I ran into two problems that I left commented above. I *must* prime the command with a _dummy_ `canExecute` before setting up the observable binding. If I don't do this, the first (or perhaps more) call to `canExecute` returns false. it's hard to tell why that is happening, but it could be something I'm doing wrong (i'm creating the command with `public someCommand = wx.asyncCommand<string>(x => Rx.Observable.return(x));` so nothing out of the ordinary there. The other problem is just a dumb typing issue, I included a work around in the comments and created [an issue](https://github.com/Reactive-Extensions/RxJS/issues/984) with the RxJS repo.

Ideally i would like to create a PR for this but i don't think i'll have the time anytime soon and wanted to post this in case someone else had more time than me.

**Comment by oliverw** [comment]
Thanks for reporting. Looking into it.

**Comment by patsissons** [comment]
p.s. the *priming* I'm doing here is related to #12

**Comment by oliverw** [comment]
I know :)

**Comment by oliverw** [comment]
Appreciate your effort. Please turn it into a proper PR and it will most likely be accepted!

**Comment by patsissons** [comment]
sounds good, i'll try and write a proper PR this weekend.
