### ISSUE TITLE
Allow list to reset using a new inner array

### ISSUE THREAD

**Issue by patsissons** [WebRxJS/WebRx#15]
I was just thinking about how to solve this and decided this is probably best done internal to the wx framework. To goal is to replace the internal list with a new list (or alternatively replace the internal list contents with those from a new list), then generate a reset notification.

The use case for this feature request is "user clicks a button, new data is fetched async, list contents are replaced, UI renders updated list contents"

I think the functionality already exists to do this (via suppress, clear, addRange, dispose) but a more convenient method would be to simply allow `reset(newData)`

Thoughts?

**Comment by oliverw** [comment]
The *suppressChangeNotifications -> clear -> addRange -> dispose* cycle sounds like the way to go. Should be easy enough to be rolled into a new utility method on <code>ObservableList</code>.

**Comment by patsissons** [comment]
were you thinking of adding this functionality to the `reset` function or making a whole new function for it?

my original idea was to do something like
```ts
    public reset(contents?: Array<T>): void {
        if (contents == null) {
            this.publishResetNotification();
        } else {
            let suppress = this.suppressChangeNotifications();
            this.clear();
            this.addRange(contents);
            suppress.dispose();
        }
    }
```
