### ISSUE TITLE
More modularity in the Framework

### ISSUE THREAD

**Issue by Samvrie** [WebRxJS/WebRx#17]
Hi,
Is there any plan to make *WebRx* more **modular**?
I would like to introduce *WebRx* in a company project, but  we are not going to use the all of features *(Routing...etc)*.

A bit in the idea of **Aurelia** or the new **ASP.NET 5** stack.
It would be really nice if we could register what we would like to use from the library instead of having the whole package.

Btw, the library is really awesome, keep up the great work!

**Comment by oliverw** [comment]
This is already possible. The "dist" folder contains everything neatly packaged as ES6 classes. When combined with a ES6 transpiler such as Babel you can really cherry-pick the features you need.

**Comment by Samvrie** [comment]
Thanks for the information!
Sorry I didn't dig in the source code to find out that it is already possible!
