### ISSUE TITLE
Type annotations on whenAny are incorrect

### ISSUE THREAD

**Issue by milutinovici** [WebRxJS/WebRx#21]
Specifically it's the selector typing that should be changed.
Currently it's:
```typescript
selector: (T1) => TRet
```
Which means function that takes parameter T1 of type any, and returns a value of type TRet.

And it should be changed to:
```typescript
selector: (a1: T1) => TRet
```
Which means function that takes parameter a1 of type T1, and returns a value of type TRet.

So the entire signature would be:
```typescript
function whenAny<TRet, T1>(arg1: wx.IObservableProperty<T1> | Rx.IObservable<T1>, selector: (a1: T1) => TRet): Rx.Observable<TRet>;
```
Same goes for all the overloads.

**Comment by oliverw** [comment]
:+1:
