### ISSUE TITLE
Components registered without viewModel ignore params

### ISSUE THREAD

**Issue by milutinovici** [WebRxJS/WebRx#31]
The docs clearly state:

>If no viewmodel is given, the component is treated as a simple block of HTML that will be bound to any parameters passed to the component.

The component doesn't bind to parameters, but the context of the parrent.

```typescript
function ViewModel() {
    this.original = 123;
}
wx.app.component("c1", { template: "<p data-bind='text: param'></p>" });
wx.app.component("c2", { template: "<p data-bind='text: original'></p>" });
```
```html
<c1 params="param: original"></c1> // doesn't work
<c2 params="param: original"></c2> // works
```

**Comment by oliverw** [comment]
This is working by design and unfortunately the docs are wrong. Thanks for pointing this out.
