### ISSUE TITLE
Can't subscribe to errors when using toProperty()

### ISSUE THREAD

**Issue by patsissons** [WebRxJS/WebRx#36]
I noticed that when using `toProperty()` on an observable stream, the error subscription is not easily accessible. We can inject an overrided default exception handler on the `IWebRxApp` but that's not really a reliable solution.

My suggestion would be to change the signature of `toProperty()` to allow supplying an error handler delegate. Currently the signature is `function toProperty(initialValue?: any, scheduler?: Rx.IScheduler)` and we likely want to put the handler before the scheduler, so this means that it would become a breaking change. But hopefully not too many people are using custom schedulers at this point.

I'm open to other thoughts on this issue too, which could involve just exposing `thrownExceptions` on a new `IReadOnlyObservableProperty<T>` interface. (this is less desirable since it now requires two statements to produce an error handling observable property).

**Comment by patsissons** [comment]
I was just thinking about this today and I think a much better approach is to create a new function to support error handling (such as `.catchExceptions(...)`) and simply return the source `IReadOnlyObservableProperty<T>`.

This means we could do something like the following
```
public myProp = myObservable
    .toProperty()
    .catchExceptions(x => {
         // do something...
     })
```

perhaps a better name than `catchExceptions`, but that's the general idea. Super noninvasive, no breaking changes, opt-in error handling strategy.

Thoughts?

**Comment by oliverw** [comment]
@patsissons Could you provide a PR for this? This issue is currently the only thing blocking the upcoming 1.5 Release and I'm currently so swamped in work that I hardly have the time to work on this.

**Comment by patsissons** [comment]
Sure, i can send in a PR today. Any thoughts on the function name?
