### ISSUE TITLE
Extract modules to different repositories.

### ISSUE THREAD

**Issue by nmabhinandan** [WebRxJS/WebRx#4]
Extract modules like router, templating engine to their own repositories so that they can be used individually and for better contribution experience.

**Comment by oliverw** [comment]
What do you mean with "extract". At the moment the framework does not come with built-in modules expect the *app* module which is required for basic operation. 

I completely agree with you though that additional modules should not be part of the core and we are even planning to create a browsable public module repository.

**Comment by nmabhinandan** [comment]
Something like aurelia does where each module with single responsibility has it's own repository and it is required by the framework via bower or jspm. The great thing about that approach is that one can use some modules like router without using the whole framework.

**Comment by oliverw** [comment]
I see what you mean. This will happen as part of WebRx's switch to Typescript 1.5 which is already under way.

**Comment by nmabhinandan** [comment]
Great. Where can I contribute? Is it under a separate branch?

**Comment by oliverw** [comment]
https://github.com/WebRxJS/WebRx/commits/ts15

**Comment by oliverw** [comment]
@nmabhinandan I'd advise against contributing changes regarding modularization until I'm done with the initial pass for that because the branch will be pretty much in flux and chances for collisions will be high.

**Comment by nmabhinandan** [comment]
:+1:

**Comment by oliverw** [comment]
Done 

147c80c6575f0098918811e37ec349e81aa7012c
