### ISSUE TITLE
Manual navigation in Router demo

### ISSUE THREAD

**Issue by rusco** [WebRxJS/WebRx#5]
Navigating manually to this link: 
[http://webrxjs.org/examples/router-demo/contacts](http://webrxjs.org/examples/router-demo/contacts) 
Throws an error. 

Manual navigation should be possible, it works for the root url:
[http://webrxjs.org/examples/router-demo/](http://webrxjs.org/examples/router-demo/).

Is this just an issue of the demo setup or not yet implemented in the router ?

**Comment by oliverw** [comment]
@rusco Actually both. Thanks for reporting!

**Comment by oliverw** [comment]
Fixed 7155b91273c8320488b6ba907954474293f18a13
