### ISSUE TITLE
TodoMVC example

### ISSUE THREAD

**Issue by rusco** [WebRxJS/WebRx#6]
the canonical http://todomvc.com/ implementation is missing.

(I will look into this, if anyone is already working on this plz get in touch...)

**Comment by oliverw** [comment]
Do you mean [this](https://t.co/b1TkQhahH4) ?

**Comment by rusco** [comment]
Cool, I came too late to the party !

What about linking to the TodoMVC Repo somewhere on the Main website ? At least I can not (yet) see any info.

Vue.js for example shows the TodoMVC App as integral part of the examples:
http://vuejs.org/examples/todomvc.html

**Comment by oliverw** [comment]
@rusco Excellent idea. The examples section of the site is due for a major overhaul anyway.

**Comment by oliverw** [comment]
TodoMVC is now directly integrated into the example browser:

http://webrxjs.org/examples/todomvc
