### ISSUE TITLE
Create a gitter channel 

### ISSUE THREAD

**Issue by SekibOmazic** [WebRxJS/WebRx#7]
and link it both to the github page and webrxjs.org

**Comment by oliverw** [comment]
While a good idea in theory, I don't think we've reached the critical mass of users before such a channel would really make sense.

**Comment by omidkrad** [comment]
@oliverw I think you can partner/collaborate with the [Aurelia](http://aurelia.io) project with some of the interesting concepts in your project. Join forces! :fist:

**Comment by adicirstei** [comment]
@oliverw, I think this would be good approach to reach a certain adoption weight. 
So, I give a +1 to the idea.

**Comment by oliverw** [comment]
WebRx now has its own gitter channel: https://gitter.im/WebRxJS

**Comment by jskulavik** [comment]
I think you need to create a room or allow new members to join and create a new one as there's no option to join, no rooms listed.  Thanks for creating the channel though! 
![webrxjsg](https://cloud.githubusercontent.com/assets/2044176/10732043/e6ede264-7bbd-11e5-904d-11b31eb6c379.PNG)

**Comment by oliverw** [comment]
Done. Thanks for reporting.
