### ISSUE TITLE
What about custom bindings?

### ISSUE THREAD

**Issue by milutinovici** [WebRxJS/WebRx#9]
As far as I can see, there are no custom bindings, a la knockout. Are they going to be added?

**Comment by oliverw** [comment]
@milutinovici Custom Bindings are fully supported - just not currently documented because writing custom bindings is currently a bit more involved than in Knockout. But you are totally right, this needs to be documented. I'm going to update this thread with a simple example later today.

**Comment by milutinovici** [comment]
Thanks. Looking forward to seeing the updated docs.

**Comment by oliverw** [comment]
It is now possible to register custom bindings without having to implement a full featured binding-handler.

**Example: Stock text-Binding implemented as a custom-binding**

```
wx.app.binding('custom-text', (el: HTMLElement, value: any, compiled: any, ctx: wx.IDataContext, domManager: wx.IDomManager, 
    state: any, cleanup: Rx.CompositeDisposable, module: wx.IModule)=> {
    if ((value === null) || (value === undefined))
        value = "";
    else
        value = wx.unwrapProperty(value);

    el.textContent = value;
});
```

**Example: Stock Value-Binding implemented as a custom-binding**

```
wx.app.binding('custom-value', (el: HTMLElement, value: any, compiled: any,
    ctx: wx.IDataContext, domManager: wx.IDomManager, state: any, cleanup: Rx.CompositeDisposable, module: wx.IModule)=> {
    if(!state.isSubscribed) {
        // update model
        cleanup.add(Rx.Observable.fromEvent(el, "change").subscribe(x=> {
            value((<HTMLInputElement> el).value);
        }));
        
        state.isSubscribed = true;
    }

    // update dom
    var result = (value === null) || (value === undefined) ? "" : wx.unwrapProperty(value);
    (<HTMLInputElement> el).value = result;
});
```
